### ISSUE TITLE
No obvious solution for encoding-aware matching.

### ISSUE THREAD

**Issue by kentfredric** [dagolden/Path-Iterator-Rule#14]
Consider if you have a directory tree, with files of unknown encoding.

If you're simply writing a tool that checks for end of line padding, using

`line_matches(qr/\s+$/)` 

Is simply not an option, because it, unless specified, assumes UTF-8, which means files with ISO-8851-1 characters gives lots of fun errors. 

And trying to override the encoding for the matcher seems like the wrong option too, because encoding is a property of the file ( and in some cases, a property of the line of the file) that is being decoded.

As such, there's not really a way to even attempt to determine encoding from the file itself and use that value for matching, you have to simply assert "Well, everything has to be this encoding" and hope you're right about that.

I see you can pass layers to 

`line_matches(":encoding(iso-8859-1)", qr// );`

But that seems misguided as forcing a single encoding on all files prior to performing the match seems like something that could only ever be expected to result in the wrong outcomes. 

When I say "( and in some cases, a property of the line of the file)"

By that I mean, Perl code, which has the unfortunate effect of being `iso-88591-1` right up until the first `use utf8` pragma, or even worse, right up to the first `=encoding UTF-8` pragma.

And some of the files I find sticky messes in have 

`=encoding ISO-8859-1`  Pod, which to me means:

```perl
# START
# ISO-88591
use utf8;   # UTF8 begins
....
=encoding ISO-8859-1   # ISO 88591-1 starts
asdfrh
=cut  # Returns to UTF8
....
```

It may not mean that, but the mess of how its implemented suggests that.

**Comment by xdg** [comment]
I don't think there's a good solution so I'm closing this issue.
