### ISSUE TITLE
Feature request: return n file names instead of just 1

### ISSUE THREAD

**Issue by lbe** [dagolden/Path-Iterator-Rule#23]
I wish PIR would allow me to specify the number of files to return instead of just returning a single file.  Something with functionality similar to:

<code>
use File::Which qw(which);

sub get_dir_file_list_iter {
    my $dir = shift;

    my $FIND = which 'find';
    my $CMD = qq/$FIND -L "$dir" -type f -print/;

    return (
        sub {
            my $chunk_size = shift // 1;
            my @ary;
            while ( my $fn = <$FH> ) {
                chomp $fn;
                push( @ary, $fn );
                last if @ary == $chunk_size;
            }
            return (@ary);
        }
    );
}
</code>

Sorry for the non-perlish example, but it is the quick and dirty I had to replace PIR with to get performance up on an MCE program.

Thanks,

lbe

**Comment by xdg** [comment]
Have you tried any of the suggestions in the [PERFORMANCE](https://metacpan.org/pod/Path::Iterator::Rule#PERFORMANCE) section of the docs?

Returning N files vs one only eliminates the subroutine call overhead -- and while that's not trivial, each invocation does a lot of other logic (and subroutine calls) for matching rules that might well dwarf the impact of the iterator subroutine calls.

Your example using `find` implies you aren't looking for a fully lazy iterator.  And if you're doing a piped-open, you're also benefiting from parallelism, as your OS can run the find in concert with your Perl code processing the results.

All of which is to say that I don't think your feature request would actually give the performance benefit you desire, so I'm going to close this as a "Won't fix" issue.

**Comment by lbe** [comment]
Given your explanation, I agree.  Thank you for the consideration and explanation!
