### ISSUE TITLE
Testing path, a la find(1) -path and -ipath?

### ISSUE THREAD

**Issue by cxw42** [dagolden/Path-Iterator-Rule#25]
Dumb question, but my Google-fu is failing me.  Is there any more self-documenting way to test the full path (not basename) than `and(sub { /whatever path pattern/ })`?  That works fine, but I'm wondering if there's a `path` or `ipath` method in this or a child module that I can't find at the moment.  The behaviour I am looking for is analogous to find(1)'s `-path` and `-ipath`.  If not, please consider this a feature request for `sub path` and `sub ipath` :) .  

Thanks!

**Comment by xdg** [comment]
Thanks for the question.  I think a custom sub is a simple, self documenting way of doing it.  Whatever your logic is, you can see exactly how it works.  I'm not away of something that offers it, and I'm not inclined to add it, as I think its use-case is rare enough that a custom sub is a sufficient answer.
