### ISSUE TITLE
opendir() errors not handled

### ISSUE THREAD

**Issue by LouisStrous** [dagolden/Path-Iterator-Rule#27]
Occasionally Path::Iterator::Rule gives me error messages

    readdir() attempted on invalid dirhandle $dh at myscript.pl line N

I've tracked the problem down to the `opendir( my $dh, $string_item)` call at line 250 in sub `_iter` in Path/Iterator/Rule.pm.  If that `opendir` call fails then the subsequent `readdir $dh` call produces the error message.  In my case the reason for the `opendir` failure is that access to the directory ('C:/Users/.NET v4.5' on a Windows 10 system) is denied.

Could you change the code to produce a more informative error message, for example the same message that you produce on line 234 if a directory is found to not be readable?  For example, something like

    my $dh;
    if (not opendir( $dh, $string_item )) {
      warnings::warnif("Directory '$string_item' is not readable.  Skipping it");
      return;
    }

I've modified my local copy of Rule.pm like that and now get more informative messages like

    Directory 'C:/Users/.NET v4.5' is not readable.  Skipping it at myscript.pl line N

and I can suppress those messages using `no warnings;` if I want -- unlike the original messages.

Regards,
Louis Strous

**Comment by xdg** [comment]
It's interesting that `-r <directory>` succeeds, but the subsequent open fails, but empirically it's a bug and needs to be fixed.  Thanks for the report.

**Comment by xdg** [comment]
Shipped to CPAN as 1.015
